ml-small:
  user_col: "userId"
  item_col: "movieId"
  rating_col: "rating"
  SVDs:
    k:
      tune: true
      min: 1
      max: 40
      step_size: 1
      default: 20
      tol: 2e-3
      selection: "min_param"
  FunkSVD:
    n_factors:
      tune: true
      min: 1
      max: 200
      step_size: 1
      default: 20
      tol: 4e-3
      selection: "min_param"
    reg:
      tune: true
      min: 0.005
      max: 0.1
      step_size: 0.001
      default: 0.02
      tol: 2e-3
      selection: "min"
    lr:
      tune: true
      min: 0.005
      max: 0.1
      step_size: 0.001
      default: 0.01
      tol: 2e-3
      selection: "max_param"
    n_epochs:
      tune: true
      min: 10
      max: 100
      step_size: 1
      default: 30
      tol: 2e-3
      selection: "min_param"

